### ISSUE TITLE
mobx.js

### ISSUE THREAD

**Issue by transtone** [b5156/mobx-wxapp#3]
项目里的 mobx.js 文件做过什么修改吗，可以用 mobx 官方项目里的最新 4.x 版替换吗？

**Comment by yanlee26** [comment]
`Cannot read property 'mode' of undefined;at api onAppEnterBackground callback function
TypeError: Cannot read property 'mode' of undefined`

切后台有报错。。。

**Comment by lbqdly** [comment]
> 项目里的 mobx.js 文件做过什么修改吗，可以用 mobx 官方项目里的最新 4.x 版替换吗？

没做修改，可以用最新的官方包。

**Comment by lbqdly** [comment]
> `Cannot read property 'mode' of undefined;at api onAppEnterBackground callback function TypeError: Cannot read property 'mode' of undefined`
> 
> 切后台有报错。。。

看上去像是微信onAppEnterBackground使用的时候报错了，你检查一下这个api的使用和'mode'关键字
